// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZg9R0PClnxVGkFPER2poLKjMhVJnAjnI',
    appId: '1:507317356728:web:a13f8b0f0a52a145a9cc4d',
    messagingSenderId: '507317356728',
    projectId: 'buktor-grow-853e3',
    authDomain: 'buktor-grow-853e3.firebaseapp.com',
    storageBucket: 'buktor-grow-853e3.appspot.com',
    measurementId: 'G-K6255V1YWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Qw0di3cOWLMkpAEcRgRQalw8EzQn0-U',
    appId: '1:507317356728:android:b9364aeb185b9026a9cc4d',
    messagingSenderId: '507317356728',
    projectId: 'buktor-grow-853e3',
    storageBucket: 'buktor-grow-853e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhzzR0aa3Y13zExmBnqIhh0KvluLxyL6M',
    appId: '1:507317356728:ios:93e1abdeb6cae6a0a9cc4d',
    messagingSenderId: '507317356728',
    projectId: 'buktor-grow-853e3',
    storageBucket: 'buktor-grow-853e3.appspot.com',
    iosBundleId: 'com.cblu.buktorgrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhzzR0aa3Y13zExmBnqIhh0KvluLxyL6M',
    appId: '1:507317356728:ios:93e1abdeb6cae6a0a9cc4d',
    messagingSenderId: '507317356728',
    projectId: 'buktor-grow-853e3',
    storageBucket: 'buktor-grow-853e3.appspot.com',
    iosBundleId: 'com.cblu.buktorgrow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZg9R0PClnxVGkFPER2poLKjMhVJnAjnI',
    appId: '1:507317356728:web:5010a52f38bbbbd6a9cc4d',
    messagingSenderId: '507317356728',
    projectId: 'buktor-grow-853e3',
    authDomain: 'buktor-grow-853e3.firebaseapp.com',
    storageBucket: 'buktor-grow-853e3.appspot.com',
    measurementId: 'G-0QSDKBK7TX',
  );
}
